from django.urls import path
from chef_table_app import views

urlpatterns = [
    path('',views.chef_page),
    path('login',views.login),
    path('checkemail',views.checkemail),
    path('logincode',views.logincode),
    path('adminhome',views.adminhome),
    path('userhome',views.userhome),
    path('chefhome',views.chefhome),
    path('register',views.register),
    path('registerchef',views.registerchef),
    path('reg_code_user',views.reg_code_user),
    path('reg_code_chef',views.reg_code_chef),
    path('admin_view_user',views.admin_view_user),
    path('add_events',views.add_events),
    path('events',views.events),
    path('view_user',views.view_user),
    path('view_chef',views.view_chef),
    path('c_profile',views.c_profile),
    path('view_profile',views.view_profile),
    path('delete_events/<id>',views.delete_events),
    path('approve_chef/<id>',views.approve_chef),
    path('reject_chef/<id>',views.reject_chef),
    path('block_user/<id>',views.block_user),
    path('unblock_user/<id>',views.unblock_user),
    path('history_chef/<id>',views.history_chef),
    path('edit_profile',views.edit_profile),
    path('edit_profile_post',views.edit_profile_post),
    path('updateprofile', views.updateprofile),
    path('BookNow/<id>', views.BookNow),
    path('userhome_search', views.userhome_search),
    path('BookNow_post', views.BookNow_post),
    path('food_item_add', views.food_item_add),
    path('food_item_view', views.food_item_view),
    path('food_item_view_post', views.food_item_view_post),
    path('food_item_view_search', views.food_item_view_search),
    path('delete_fooditem/<id>', views.delete_fooditem),
    path('edit_fooditem/<id>', views.edit_fooditem),
    path('food_item_update', views.food_item_update),
    path('Bookdishes', views.Bookdishes),
    path('Order_dishes', views.Order_dishes),
    path('chef_view_booking', views.chef_view_booking),
    path('view_dishes_chef/<id>', views.view_dishes_chef),
    path('view_booking_dishes_user/<id>', views.view_booking_dishes_user),
    path('accept_booking', views.accept_booking),
    path('reject_booking', views.reject_booking),
    path('my_booking', views.my_booking),
    path('my_booking_post', views.my_booking_post),
    path('payment/<id>/<amt>',views.payment),
    path('on_payment_success', views.on_payment_success),
    # path('feedback/<id>', views.feedback),
    path("add_feedback",views.add_feedback),
    path("add_complaint", views.add_complaint),
    path('complaint_user', views.complaint_user),
    path('admin_view_report', views.admin_view_report),
    path('chef_view_booking_search', views.chef_view_booking_search),

]

