# Generated by Django 5.0.3 on 2024-09-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_table_app', '0002_remove_usertable_pin_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheftable',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usertable',
            name='image',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
