# Generated by Django 5.0.3 on 2024-10-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef_table_app', '0007_rename_quantity_bookingtable_mealstype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingtable',
            old_name='ChefTable',
            new_name='CHEF',
        ),
    ]
