# Generated by Django 5.0.3 on 2024-10-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_table_app', '0009_alter_bookingtable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodtable',
            name='Cuisine',
            field=models.CharField(default='Breakfast', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodtable',
            name='Image',
            field=models.FileField(default='sample.png', upload_to=''),
            preserve_default=False,
        ),
    ]
