# Generated by Django 5.0.3 on 2024-10-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_table_app', '0012_remove_bookingtable_mealstype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtable',
            name='Details',
            field=models.TextField(),
        ),
    ]
