# Generated by Django 5.0.3 on 2024-10-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_table_app', '0013_alter_foodtable_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='num_mem',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
