# Generated by Django 5.0.3 on 2024-10-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_table_app', '0014_bookingtable_num_mem'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetailstable',
            name='Count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingdetailstable',
            name='Price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
