# Generated by Django 5.0.3 on 2024-10-24 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef_table_app', '0016_complient_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='complient',
            name='BOOKING',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chef_table_app.bookingtable'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complient',
            name='reply',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
